module.exports = {
  pageAccessToken: "EAAEvFFNRaBMBADq6JBuf2hcZCZC2HOeZAEuoPfJCUMeNPKxPZBvKByjFucL1vmkakhcdJIVH8je8XQBI7cqXPJm9c6CuGF9TK77NMtcopEWjN8nJqdOzlPuIsJuH4PZCk1UQHeqD6COKJ3LZBwAHkRurJoKLz1GIFfTgzocstFZAAZDZD",
  fbValidationToken: "openToken"
}
